/**
 * Central RBAC vocabulary.
 *
 * Keys here are the single source of truth used by the seed script,
 * the authorize() middleware, and the frontend. Change here + reseed
 * to update permissions.
 */

export const ROLE_KEYS = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  CENTRAL_ADMIN: 'CENTRAL_ADMIN',
  UNIT_ADMIN: 'UNIT_ADMIN',
  INSPECTOR: 'INSPECTOR',
  VIEWER: 'VIEWER',
} as const;

export type RoleKey = (typeof ROLE_KEYS)[keyof typeof ROLE_KEYS];

export const PERMISSION_KEYS = {
  USER_MANAGE: 'user.manage',
  USER_VIEW: 'user.view',
  ROLE_MANAGE: 'role.manage',
  UNIT_MANAGE: 'unit.manage',
  UNIT_VIEW: 'unit.view',
  DEPARTMENT_MANAGE: 'department.manage',
  DEPARTMENT_VIEW: 'department.view',
  EQUIPMENT_MANAGE: 'equipment.manage',
  EQUIPMENT_VIEW: 'equipment.view',
  CHECKLIST_MANAGE: 'checklist.manage',
  CHECKLIST_VIEW: 'checklist.view',
  INSPECTION_PERFORM: 'inspection.perform',
  INSPECTION_VIEW: 'inspection.view',
  CORRECTIVE_ACTION_CREATE: 'corrective_action.create',
  CORRECTIVE_ACTION_CLOSE: 'corrective_action.close',
  CORRECTIVE_ACTION_VIEW: 'corrective_action.view',
  REPORT_VIEW: 'report.view',
  AUDIT_VIEW: 'audit.view',
} as const;

export type PermissionKey =
  (typeof PERMISSION_KEYS)[keyof typeof PERMISSION_KEYS];

/**
 * Role → permission mapping used by the seed script.
 * See docs/RBAC.md for the human-readable version.
 */
export const ROLE_PERMISSIONS: Record<RoleKey, PermissionKey[]> = {
  SUPER_ADMIN: Object.values(PERMISSION_KEYS),

  CENTRAL_ADMIN: [
    PERMISSION_KEYS.USER_MANAGE,
    PERMISSION_KEYS.USER_VIEW,
    PERMISSION_KEYS.UNIT_MANAGE,
    PERMISSION_KEYS.UNIT_VIEW,
    PERMISSION_KEYS.DEPARTMENT_MANAGE,
    PERMISSION_KEYS.DEPARTMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.CHECKLIST_MANAGE,
    PERMISSION_KEYS.CHECKLIST_VIEW,
    PERMISSION_KEYS.INSPECTION_PERFORM,
    PERMISSION_KEYS.INSPECTION_VIEW,
    PERMISSION_KEYS.CORRECTIVE_ACTION_CREATE,
    PERMISSION_KEYS.CORRECTIVE_ACTION_CLOSE,
    PERMISSION_KEYS.CORRECTIVE_ACTION_VIEW,
    PERMISSION_KEYS.REPORT_VIEW,
    PERMISSION_KEYS.AUDIT_VIEW,
  ],

  UNIT_ADMIN: [
    PERMISSION_KEYS.USER_MANAGE,
    PERMISSION_KEYS.USER_VIEW,
    PERMISSION_KEYS.UNIT_VIEW,
    PERMISSION_KEYS.DEPARTMENT_MANAGE,
    PERMISSION_KEYS.DEPARTMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_MANAGE,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.CHECKLIST_VIEW,
    PERMISSION_KEYS.INSPECTION_PERFORM,
    PERMISSION_KEYS.INSPECTION_VIEW,
    PERMISSION_KEYS.CORRECTIVE_ACTION_CREATE,
    PERMISSION_KEYS.CORRECTIVE_ACTION_CLOSE,
    PERMISSION_KEYS.CORRECTIVE_ACTION_VIEW,
    PERMISSION_KEYS.REPORT_VIEW,
  ],

  INSPECTOR: [
    PERMISSION_KEYS.UNIT_VIEW,
    PERMISSION_KEYS.DEPARTMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.CHECKLIST_VIEW,
    PERMISSION_KEYS.INSPECTION_PERFORM,
    PERMISSION_KEYS.INSPECTION_VIEW,
    PERMISSION_KEYS.CORRECTIVE_ACTION_CREATE,
    PERMISSION_KEYS.CORRECTIVE_ACTION_VIEW,
    PERMISSION_KEYS.REPORT_VIEW,
  ],

  VIEWER: [
    PERMISSION_KEYS.UNIT_VIEW,
    PERMISSION_KEYS.DEPARTMENT_VIEW,
    PERMISSION_KEYS.EQUIPMENT_VIEW,
    PERMISSION_KEYS.CHECKLIST_VIEW,
    PERMISSION_KEYS.INSPECTION_VIEW,
    PERMISSION_KEYS.CORRECTIVE_ACTION_VIEW,
    PERMISSION_KEYS.REPORT_VIEW,
  ],
};
